### PR TITLE
assignment - 01.28 - movement

### PR DESCRIPTION
**Pull request by Cody-Jiang-Zhihong**
https://github.com/Cody-Jiang-Zhihong/pipeworld

### CODE REVIEW

**Comment by tycobbb** [comment]
hi cody, thanks, looks good!

there's one thing we need to fix, that is admittedly my fault. macos creates these `.DS_Store` files we don't want in the repo. unless you feel very confident, please get some help in lab to do fix it, rather than doing it on your own! here's the commands we'll need to run to fix it.

if you have any changes:

```sh
git add .
git stash
```

then, grab files we need from the _class repo_ (which we will call "upstream"):

```sh
git remote add upstream git@github.com:introtogamedev/pipeworld.git
git fetch upstream

git checkout upstream/main .gitigtnore
```

then, remove the offending file so that `git` can't see it anymore:

```sh
git rm --cached .DS_Store
git commit -m "remove ds store"
git push
```

finally, if you had changes and want to bring them back (**only** do this if you did the first set of commands!):

```sh
git stash pop
```

**Review by tycobbb — APPROVED** [review]
great, thank you!

**Comment by Cody-Jiang-Zhihong** [comment]
Morning professor!

I am kinda sorry for adding the ds_store file into my repo since I forgot
to add it into gitigtnore. I just asked the TA in the lab and now it's
gone! The gitigtnore also has the .DS_Store in it rn! Problem Solved. :-)
[image: image.png]

Bests,
Cody

**Comment by tycobbb** [comment]
no need to be sorry, and in any case it was my fault!

**Pull request merged**
