### PR TITLE
assignment i - intutition

### PR DESCRIPTION
**Pull request by conceptualhenry**
Sorry this is late! I forgot it was supposed to be at 6! Also I can't fix the above collisions :/

### CODE REVIEW

**Comment by tycobbb** [comment]
heya, please link your github project page, e.g. https://github.com/users/tycobbb/projects/3/views/1 (not this one though, this is mine)! and please follow [these instructions](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-visibility-of-your-projects#changing-project-visibility) to make it public.

**Comment by conceptualhenry** [comment]
Just made it public - should I put the link anywhere else specific?
https://github.com/users/conceptualhenry/projects/1/views/1
Also I'll push it again right now, let me know if it's working!

**Comment by tycobbb** [comment]
that's for the link! it works! i merged the pull request anyways so i can start reviewing everyone's work.

**Comment by conceptualhenry** [comment]
Awesome thank you!

**Pull request merged**
