### PR TITLE
1/29 assignment

### PR DESCRIPTION
**Pull request by Sapiens-wx**

### CODE REVIEW

**Comment by tycobbb** [comment]
hi rocky! looks good!

we do have to fix one thing. your project (`SuperMarioClone`) and your `README.md` should be in a folder named `rocky`. unless you feel very confident, please get some help in lab to do fix it, rather than doing it on your own! here's the commands we'll need to run to fix it.

if you have any changes:

```sh
git add .
git stash
```

then, move your work into a new directory with your name:

```sh
mkdir rocky
mv ty/README.md rocky
mv SuperMarioClone rocky
```

then, repair the files that we don't want to change by grabbing the version from the _class repo_ (which we will call "upstream"):

```sh
git remote add upstream git@github.com:introtogamedev/pipeworld.git
git fetch upstream

git checkout upstream/main README.md
git checkout upstream/main ty/README.md
```

then, commit and push the fix:

```sh
git add .
git commit -m "fix conflicts, move work into my folder"
git push
```

finally, if you had changes and want to bring them back (**only** do this if you did the first set of commands!):

```sh
git stash pop
```

**Comment by Sapiens-wx** [comment]
Hi Ty,

Thank you for telling me how to fix it. I have fixed the problem and pushed it to my fork on github. Do I need to submit another pull request? It seems like I cannot create another pull request on github.

Thanks,

Rocky

**Comment by tycobbb** [comment]
nice job! it looks like you still need to restore the readme from my folder, though!

if you have changes

```sh
git add .
git stash
```

if you did this last time, skip this step! otherwise:

```sh
git remote add upstream git@github.com:introtogamedev/pipeworld.git
```

then, restore my readme:

```sh
git fetch upstream
git checkout upstream/main ty/README.md
```

then, commit and push the fix:

```sh
git add .
git commit -m "restore ty's readme =)"
git push
```

finally, bring back your changes (if you did the first set of commands!):

```sh
git stash pop
```

**Comment by Sapiens-wx** [comment]
Hi Ty,

I have just restored the readme file from your folder.

Rocky

**Pull request merged**
